modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/LilRicefield/saints-dragons/issues"

[[mods]]
modId = "saintsdragons"
version = "${version}"
displayName = "Saint's Dragons"
authors = "Leon Saint"
description = "Adds animated, AI-driven dragons or wyverns to Minecraft."

[[mixins]]
config = "saintsdragons-neoforge.mixins.json"

[[mixins]]
config = "saintsdragons-neoforge-multipart.mixins.json"

[[dependencies.saintsdragons]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.saintsdragons]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.saintsdragons]]
modId = "geckolib"
type = "required"
versionRange = "[4.8.2,)"
ordering = "AFTER"
side = "BOTH"
